# Generated by Django 3.1.6 on 2021-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210210_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('A', 'Article'), ('N', 'News')], default='N', max_length=1),
        ),
    ]
